apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-303
  name: dev-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "create", "update", "patch", "delete", "watch", "list"]
